### ISSUE TITLE
Javascript test error with OAG 7.4.0

### ISSUE THREAD

**Issue by cliffano** [cliffano/endoflife.date-api-clients#1]
With OAG 7.4.0, Javascript lang failed on 2 parts:

A. npm test

```
  1) "before each" hook for "should call getApiAllJson successfully":
     TypeError: EndoflifeDate.CycleCycle is not a constructor
      at Context.<anonymous> (test/model/CycleCycle.spec.js:31:16)
      at processImmediate (node:internal/timers:478:21
```

B. mocha --timeout 5000 test/javascript/

```
  1) getApi
       getApiProductCycleJson
         should respond with product cycle information:
     Uncaught TypeError: _CycleEol.default.constructFromObject is not a function
    at Function.constructFromObject (/opt/workspace/clients/javascript/generated/dist/model/Cycle.js:75:45)
    at Function.convertToType (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:610:25)
    at ApiClient.deserialize (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:373:24)
    at /opt/workspace/clients/javascript/generated/dist/ApiClient.js:491:29
    at Request.callback (/opt/workspace/clients/javascrip... == undefined
  AssertionError [ERR_ASSERTION]: TypeError: _CycleEol.default.constructFromObject is not a function
      at Function.constructFromObject (clients/javascript/generated/dist/model/Cycle.js:75:45)
      at Function.convertToType (clients/javascript/generated/dist/ApiClient.js:610:25)
      at ApiClient.deserialize (clients/javascript/generated/dist/ApiClient.js:373:24)
      at /opt/workspace/clients/javascript/generated/dist/ApiClient.js:491:29
      at Request.callback (/opt/workspace/clients/javascrip... == undefined
      at callback (test/javascript/getApi.js:24:16)
      at /opt/workspace/clients/javascript/generated/dist/ApiClient.js:499:11
      at Request.callback (clients/javascript/generated/node_modules/superagent/lib/node/index.js:894:12)
      at /opt/workspace/clients/javascript/generated/node_modules/superagent/lib/node/index.js:1126:20
      at IncomingMessage.<anonymous> (clients/javascript/generated/node_modules/superagent/lib/node/parsers/json.js:22:7)
      at IncomingMessage.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1376:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  2) getApi
       getApiProductJson
         should respond with product cycle information:
     Uncaught TypeError: _CycleCycle.default.constructFromObject is not a function
    at Function.constructFromObject (/opt/workspace/clients/javascript/generated/dist/model/Cycle.js:69:49)
    at Function.convertToType (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:610:25)
    at /opt/workspace/clients/javascript/generated/dist/ApiClient.js:615:32
    at Array.map (<anonymous>)
    at Function.convertToType (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:614:25)
    at ApiClient.deseri... == undefined
```

**Comment by cliffano** [comment]
Still the same case with 7.17.0

```
Generated test
  1) "before each" hook for "should call getApiAllJson successfully":
     TypeError: EndoflifeDate.CycleCycle is not a constructor
      at Context.<anonymous> (test/model/CycleCycle.spec.js:31:16)
      at processImmediate (node:internal/timers:505:21)

Integration test
  1) getApi
       getApiProductCycleJson
         should respond without error:
     TypeError: _CycleEol.default.constructFromObject is not a function
      at Cycle.constructFromObject (/opt/workspace/clients/javascript/generated/dist/model/Cycle.js:75:45)
      at ApiClient.convertToType (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:612:25)
      at ApiClient.deserialize (/opt/workspace/clients/javascript/generated/dist/ApiClient.js:372:24)
      at /opt/workspace/clients/javascript/generated/dist/ApiClient.js:493:29
      at Request.callback (/opt/workspace/clients/javascript/generated/node_modules/superagent/lib/node/index.js:894:12)
      at /opt/workspace/clients/javascript/generated/node_modules/superagent/lib/node/index.js:1126:20
      at IncomingMessage.<anonymous> (/opt/workspace/clients/javascript/generated/node_modules/superagent/lib/node/parsers/json.js:22:7)
      at IncomingMessage.emit (node:events:520:35)
      at endReadableNT (node:internal/streams/readable:1701:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```

**Comment by cliffano** [comment]
This error occurs for both the generated javascript client test and the repo's test javascript.

**Comment by cliffano** [comment]
Still the case on 7.18.0 .
